name: Release
on:
  push:
    branches:
    - main

jobs:
  release:
    name: Release
    uses: aquasecurity/trivy/.github/workflows/reusable-release.yaml@main
    with:
      goreleaser_config: goreleaser.yml
      goreleaser_options: '--clean --timeout 90m'
    secrets: inherit
